runtime: nodejs14

env_variables:
  MONGO_URI: 'mongodb+srv://addressbook:EgNQWURfEpzIidev@cportfolio.3v9yf.gcp.mongodb.net/?retryWrites=true&w=majority'
  MONGO_NAME: 'addressBook'
  GOOGLE_MAP_API_KEY: 'AIzaSyCcgmYKvCsopODUXx4nMpv9bKKef1iGG-s'
  LOG_LEVEL: 'debug'

service: service1
